In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
url="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

names = ['sepal-length','sepal-width','peatal-length','petal-width','class']

dataset=pd.read_csv(url,names=names)

In [ ]:
dataset.head()

sepal-length  sepal-width  peatal-length  petal-width        class
0           5.1          3.5            1.4          0.2  Iris-setosa
1           4.9          3.0            1.4          0.2  Iris-setosa
2           4.7          3.2            1.3          0.2  Iris-setosa
3           4.6          3.1            1.5          0.2  Iris-setosa
4           5.0          3.6            1.4          0.2  Iris-setosa

In [ ]:
X=dataset.iloc[:,:-1].values
Y=dataset.iloc[:,4].values

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.20)

In [ ]:
from pandas.core.tools.datetimes import Scalar
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train,Y_train)

KNeighborsClassifier()

In [ ]:
Y_pred=classifier.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(Y_test,Y_pred))
print(confusion_matrix(Y_test,Y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      0.78      0.88         9
 Iris-virginica       0.85      1.00      0.92        11

       accuracy                           0.93        30
      macro avg       0.95      0.93      0.93        30
   weighted avg       0.94      0.93      0.93        30

[[10  0  0]
 [ 0  7  2]
 [ 0  0 11]]
